// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihuevyfcpvcnurwdnuig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlodWV2eWZjcHZjbnVyd2RudWlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODMxOTc5MDksImV4cCI6MjA5ODc3MzkwOX0.JbtxWAGuNC60rFIwe8LTJ3wWYTpaCNpD7s3PfDWF7S0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});